  - name: install nginx
    ansible.builtin.dnf: 
      name: nginx
      state: present
    
  - name: Enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: remove default html file
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: create app directory
    ansible.builtin.file:
      name: app
      state: directory

  - name: download the frontend application
    ansible.builtin.import_role: 
      name: common
      tasks_from: appsetup

  - name: extract application
    ansible.builtin.import_role: 
      name: common
      tasks_from: appsetup   


  - name: copy the expenses configuration
    ansible.builtin.copy: 
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
      - restated

       

