  - name: install nginx
    ansible.builtin.dnf: 
      name: nginx
      state: present
    
  - name: Enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: remove default html file
    ansible.builtin.command: rm -rf {{APP_LOCATION}}/*
      

  - name: create app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download the frontend application
    ansible.builtin.import_role: 
      name: common
      tasks_from: appsetup

  - name: extract application
    ansible.builtin.import_role: 
      name: common
      tasks_from: appsetup   


  - name: copy the expenses configuration
    ansible.builtin.template: 
      src: expense.conf.j2
      dest: /etc/nginx/default.d/expense.conf
    notify:
       restart nginx


       

