- name: installing mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysqlsetup

- name: start and enabling mysql
  ansible.builtin.import_role:
    name: common
    tasks_from: mysqlsetup

- name: assaign root password for mysql
  ansible.builtin.command: 'mysql_secure_installation --set-root-pass {{PASSWORD}}'


